version: '3.8'

services:
  # Serviço Nginx para servir a aplicação
  nginx:
    image: nginx:alpine
    container_name: sistema_medico_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - sistema_medico_network

  # Serviço PHP-FPM
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: sistema_medico_php
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - sistema_medico_network

  # Serviço MySQL
  mysql:
    image: mysql:8.0
    container_name: sistema_medico_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sistema_medico
      MYSQL_USER: sistema_medico_user
      MYSQL_PASSWORD: sistema_medico_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sistema_medico_network

networks:
  sistema_medico_network:
    driver: bridge

volumes:
  mysql_data:

